  <!-- 
    PHP version 7
  @author      Webjump Core Team <dev@webjump.com.br>
  @copyright   2021 Webjump (http://www.webjump.com.br)
  @license     http://www.webjump.com.br  Copyright
  @link        http://www.webjump.com.br 
-->

<?php

/** @var $block Magento\Framework\View\Element\Template */
?>
<section class="custom-block-footer">
  <div>
    <p class="footer-promo-news">Receba Ofertas e Novidades</p>
  </div>
    <input type="text" placeholder="nome completo"/>
    <input type="text" placeholder="e-mail"/>
    <button type="submit">ENVIAR</button>
</section>